blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/FossifyOrg/General-Discussion/discussions
    about: Please ask and answer questions here.
  - name: Something else
    url: https://github.com/FossifyOrg/General-Discussion/issues/new
    about: Please use this option only if your issue is not a bug report, a feature request, or a question. 
