blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/FossifyOrg/Gallery/discussions
    about: Please ask and answer questions here.
 - name: Something else
    url: https://github.com/FossifyOrg/General-Discussion/issues/new
    about: Create a blank issue.
